services:
  - docker

before_install:
- docker pull debian:8

script:
- docker run -v `pwd`/deb:/tmp/deb debian:8 sh -c "echo 777 > /tmp/deb/hustoj_debian_0.0.1-$TRAVIS_TAG"
- docker run -v `pwd`/deb:/tmp/deb debian:8 sh -c "echo 777 > /tmp/deb/hustoj_ubuntu_0.0.1-$TRAVIS_TAG"

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: deb/*
  skip_cleanup: true
  on:
    tags: true

